### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by babte** [cajohare/AxionLimits#3]
While the text suggest to link to the plot WITH projections, the link goes to the plot w/o projections

Thanks for checking

Plot of dimensionless coupling with projections ([pdf](https://github.com/cajohare/AxionLimits/raw/master/plots/AxionPhoton_Rescaled_NoProjections.pdf), [png](https://github.com/cajohare/AxionLimits/raw/master/plots/plots_png/AxionPhoton_Rescaled_NoProjections.png))

**Comment by babte** [comment]
Hi @cajohare  just to make sure you saw the comment above :)

**Comment by cajohare** [comment]
Thanks Babette, I think this is resolved now. I decided to take those plots off of the main page a while ago because I didn't like them much. The notebook is still there to make them though. I also have these ones: https://github.com/cajohare/AxionLimits/blob/master/docs/am.md which are similar.

If you think these plots are useful I can work on them and put them back in.

**Comment by babte** [comment]
![image](https://github.com/user-attachments/assets/53c50e76-e74f-431c-9b98-e1789b9dba30)

I may be doing something stupid (reloaded cache though), for me it still shows the link for the dimless proj.
but the link WITH projections,  goes to the plot w/o projections

am I missing something?

**Comment by cajohare** [comment]
ah sorry i was looking somewhere else, yes there was an error here, I corrected it. Thanks!

**Comment by babte** [comment]
super thanks! this repository is really very useful. Thanks for doing this
